#! /bin/bash

first=$1
last=$2
command=$3

case "$#" in
    2) dir=$(ls | egrep ^$first-)
        ;;
    3) dir=$(ls | egrep ^[0-9] | sort -g | awk "/^$first-/,/^$last-/")
        ;;
    *) echo "Invalid number of parameters"
        exit
        ;;
esac
        
# log results
touch deploy_log

for d in $dir; do
    echo -e "\nNow on $d\n"

    if [ -e $d ]; then
        cd $d;
    else
        cd ../$d;
    fi

    fab $command | tee -a ../deploy_log
done
