#! /bin/bash

# Given two numbers and a fab command,
# executes the fab command on the deployments
# in the interval, inclusive

# e.g.: allfabs 3 6 tdd
#       runs fab tdd on the the deployments
#       from Keystone (3) to Neutron (6)


case "$#" in
    2)  first=$1
        command=$2
        dir=$(ls | egrep ^$first-)
        ;;
    3)  first=$1 
        last=$2
        command=$3
        dir=$(ls | egrep ^[0-9] | sort -g | awk "/^$first-/,/^$last-/")
        ;;
    *) echo "Invalid number of parameters"
        exit
        ;;
esac
        
# log results
touch deploy_log

for d in $dir; do
    echo -e "\nNow on $d\n"

    if [ -e $d ]; then
        cd $d;
    else
        cd ../$d;
    fi

    fab $command | tee -a ../deploy_log
done
