#! /bin/bash

# hosts='controller network compute1 storage1' 
hosts='controller network compute1' 

for host in $hosts; do
    sed -i "/$host/ d" ~/.ssh/known_hosts
done

for host in $hosts; do
    ssh-copy-id root@$host
done
